spring:
  profiles:
    active: dev
  application:
    name: examination
  mvc:
    view:
      prefix: /
      suffix: .jsp

server:
  port: 8101
  servlet:
    context-path: /ex
    jsp:
      init-parameters:
        development: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  level:
    com.home.examination.mapper : debug